# Default, Defaults
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: X Market
email: to.be.mr.all.rounder@gmail.com
description: A
baseurl: "/x-market" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: "https://yamadagenki.github.io/x-market"
sass:
  style: compressed

# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
instagram: 
facebook:
google:

category_slugs:
  vitamin: "ビタミンC"

plugins:
  - jekyll-sitemap
